In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import os 
import sys

sys.path.append(os.path.abspath(os.path.join(os.getcwd(), os.pardir)))

from utils.helpers import get_db_engine 
from utils.loggers_config import logger

%matplotlib inline
sns.set(style='whitegrid')

engine = get_db_engine()

query = "SELECT * FROM processed_churn_train"

try:
    logger.info("Attempting to fetch data from PostgreSQL...")
    df = pd.read_sql(query, engine)
    logger.info(f"Data ingestion successful! Loaded {df.shape[0]} rows and {df.shape[1]} columns.")
except Exception as e:
    logger.error(f"Failed to ingest data. Error: {str(e)}")
    raise e

df.head()

[2026-05-10 22:43:37,385: INFO: 3059672025: Attempting to fetch data from PostgreSQL...]
[2026-05-10 22:43:39,771: INFO: 3059672025: Data ingestion successful! Loaded 440832 rows and 12 columns.]

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,1034.0,47,female,38.0,12.0,10,8,standard,annual,250.0,22.0,1
1,1443.0,39,female,2.0,27.0,10,24,basic,quarterly,348.0,1.0,1
2,1921.0,60,male,21.0,19.0,7,11,premium,annual,718.0,16.0,1
3,2056.0,22,female,35.0,25.0,8,22,premium,annual,805.0,8.0,1
4,3693.0,19,female,14.0,16.0,6,14,standard,annual,776.0,9.0,1

In [3]:
df_prepared = df.drop(['CustomerID'], axis=1)

In [4]:
df_prepared = pd.get_dummies(df_prepared, columns=['Gender', 'Subscription Type'], drop_first=True)

In [5]:
contract_map = {'Monthly': 1, 'Quarterly': 3, 'Annual': 12}
df_prepared['Contract Length'] = df_prepared['Contract Length'].map(contract_map)

In [6]:
df_prepared.to_sql('cleaned_churn_data', engine, if_exists='replace', index=False)

832

In [ ]:
pd.read_sql("SELECT COUNT(*) FROM cleaned_churn_data", engine)

    count
0  440832